### Test Server
GET http://localhost:8080/api/

### Get all projects
GET http://localhost:8080/api/projects/


### Get a specific project by ID
GET http://localhost:8080/api/projects/1

### Create a new project
POST http://localhost:8080/api/projects/
Content-Type: application/json

{
  "title": "New2",
  "description": "Description of the new project",
  "category": "Aquarium"
}

### Update a project
PUT http://localhost:8080/api/projects/2
Content-Type: application/json

{
  "title": "Newwwwwwww Project Title",
  "description": "Updated description",
  "category": "Aquarium"
}

### Delete a project
DELETE http://localhost:8080/api/projects/1


